version: "3.10"

services:
  db:
    image: postgres
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build: .
    command: /bin/bash -c "sleep 10; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    command: ["npx", "serve", "-s", "build"]
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
