name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Create a temporary directory
          mkdir gh-pages-temp
          cd gh-pages-temp

          # Initialize a new Git repository
          git init
          git checkout --orphan gh-pages

          # Copy built files from the main directory to the temporary directory
          cp -r ../build/* .

          # Stage changes and commit
          git add .
          git commit -m "Deploy to GitHub Pages by GitHub Actions"

          # Set the remote URL with the GitHub token for authentication
          git remote add origin-repo "https://${GITHUB_TOKEN}@github.com/username/repositoryname.git"

          # Push changes to the 'gh-pages' branch
          git push -f origin-repo gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
