name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "teoahoo@gmail.com"
          git config --global user.name "Dmitry"
          mkdir gh-pages-temp
          cd gh-pages-temp
          git init
          git checkout --orphan gh-pages

          # Copy built files from the main directory to the temporary directory
          cp -r ../build/* .

          git add .
          git commit -m "Deploy to GitHub Pages by GitHub Actions"

          # Push changes to the 'gh-pages' branch in the repository
          git remote add origin-repo https://github.com/username/repositoryname.git
          git push -f origin-repo gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
